name: AI Teacher Feedback

on:
  push:
    branches: [main, master]

jobs:
  ai_review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install google-generativeai

      - name: Generate AI Feedback
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python - <<EOF
          import os
          import google.generativeai as genai
          import subprocess


          genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
          model = genai.GenerativeModel("gemini-1.5-flash")

          # áƒ™áƒáƒ“áƒ˜áƒ¡ áƒªáƒ•áƒšáƒ˜áƒšáƒ”áƒ‘áƒ”áƒ‘áƒ˜áƒ¡ áƒáƒ›áƒáƒ¦áƒ”áƒ‘áƒ
          try:
              diff = subprocess.check_output(["git", "diff", "HEAD~1", "HEAD"]).decode("utf-8")
          except:
              diff = "áƒžáƒ˜áƒ áƒ•áƒ”áƒšáƒ˜ 'push' - áƒ™áƒáƒ“áƒ˜áƒ¡ áƒ¡áƒ áƒ£áƒšáƒ˜ áƒáƒœáƒáƒšáƒ˜áƒ–áƒ˜ áƒ¡áƒáƒ­áƒ˜áƒ áƒ áƒáƒ  áƒáƒ áƒ˜áƒ¡."

          prompt = f"áƒ¨áƒ”áƒœ áƒ®áƒáƒ  áƒžáƒ áƒáƒ’áƒ áƒáƒ›áƒ˜áƒ áƒ”áƒ‘áƒ˜áƒ¡ áƒ›áƒ™áƒáƒªáƒ áƒ˜, áƒ›áƒáƒ’áƒ áƒáƒ› áƒ¡áƒáƒ›áƒáƒ áƒ—áƒšáƒ˜áƒáƒœáƒ˜ áƒ›áƒáƒ¡áƒ¬áƒáƒ•áƒšáƒ”áƒ‘áƒ”áƒšáƒ˜. áƒ’áƒáƒ“áƒáƒ®áƒ”áƒ“áƒ” áƒáƒ› áƒ™áƒáƒ“áƒ˜áƒ¡ áƒªáƒ•áƒšáƒ˜áƒšáƒ”áƒ‘áƒ”áƒ‘áƒ¡ áƒ“áƒ áƒ“áƒáƒ¬áƒ”áƒ áƒ” áƒ›áƒáƒ™áƒšáƒ” (3-4 áƒžáƒ£áƒœáƒ¥áƒ¢áƒ˜) áƒ¤áƒ˜áƒ“áƒ‘áƒ”áƒ¥áƒ˜ áƒ¥áƒáƒ áƒ—áƒ£áƒš áƒ”áƒœáƒáƒ–áƒ”. áƒ§áƒ£áƒ áƒáƒ“áƒ¦áƒ”áƒ‘áƒ áƒ›áƒ˜áƒáƒ¥áƒªáƒ˜áƒ” áƒšáƒáƒ’áƒ˜áƒ™áƒáƒ¡ áƒ“áƒ áƒ¡áƒ˜áƒ¡áƒ£áƒ¤áƒ—áƒáƒ•áƒ”áƒ¡:\n\n{diff}"

          response = model.generate_content(prompt)

          with open("feedback.txt", "w", encoding="utf-8") as f:
              f.write("### ðŸ¤– AI áƒ›áƒáƒ¡áƒ¬áƒáƒ•áƒšáƒ”áƒ‘áƒšáƒ˜áƒ¡ áƒ¨áƒ”áƒ¤áƒáƒ¡áƒ”áƒ‘áƒ\n")
              f.write(response.text)
          EOF

      - name: Post Feedback to Summary
        run: cat feedback.txt >> $GITHUB_STEP_SUMMARY

      - name: Post Feedback as Comment (Optional)
        uses: peter-evans/commit-comment@v3
        with:
          body-path: feedback.txt
